config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :categories, except: [:edit, :update, :destroy] do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :recipe
  belongs_to :category

  validates :comment, length: { minimum: 6 }
  # bookmark must be linked to a recipe and a category, and the [recipe, category] pairings should be unique
  validates :recipe_id, uniqueness: { scope: :category_id }
  # scope groups them - makes a "pairing"/association, that's why order doesn't matter:
  # ^same as = validates :category_id, uniqueness: { scope: :recipe_id }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :recipes, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :bookmarks

  validates :description, presence: true
  validates :name, presence: true, uniqueness: true
  validates :rating, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @category = Category.find(params[:category_id])
    @bookmark = Bookmark.new
  end

  def create
    @category = Category.find(params[:category_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.category = @category

    if @bookmark.save
      redirect_to category_path(@category)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to categories_path(@bookmark.category)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :recipe_id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    # the recipes associated with every category

  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/bookmarks/new.html.erb
<h1>Add a recipe to <%= @category.name %> category</h1>
<%= simple_form_for [@category, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :recipe %>
  <%= f.submit %>
<% end %>

app/views/categories/index.html.erb
<h1>Cook book</h1>
<ul>
  <% @categories.each do |category|%>
    <li><%= link_to category.name, category_path(category) %></li>
  <% end %>
</ul>

<%= link_to 'Create a new category', category_path(:new) %>

app/views/categories/new.html.erb
<h1>Create a new Category</h1>
<%= simple_form_for [@category] do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>
<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<ul>
  <% @category.bookmarks.each do |bookmark| %>
    <li>
      <h3><%= bookmark.recipe.name %></h3>
      <p><%= bookmark.recipe.description %></p>
      <%= link_to 'Delete', bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
      <%= link_to 'Back', categories_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCookbook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>